{"id":10458,"className":"java.sql.SQLSyntaxErrorException","methodName":"SQLSyntaxErrorException","signature":"\u003cjava.sql.SQLSyntaxErrorException: void SQLSyntaxErrorException(java.lang.String,java.lang.Throwable)\u003e","javadoc":"/** \n * Constructs a \u003ccode\u003eSQLSyntaxErrorException\u003c/code\u003e object with a given \u003ccode\u003ereason\u003c/code\u003e and  \u003ccode\u003ecause\u003c/code\u003e. The \u003ccode\u003eSQLState\u003c/code\u003e is  initialized to \u003ccode\u003enull\u003c/code\u003e and the vendor code is initialized to 0. \u003cp\u003e\n * @param reason a description of the exception.\n * @param cause the underlying reason for this \u003ccode\u003eSQLException\u003c/code\u003e (which is saved for later retrieval by the \u003ccode\u003egetCause()\u003c/code\u003e method); may be null indicatingthe cause is non-existent or unknown.\n * @since 1.6\n */\n","tf":{"freq":{"may":1,"except":3,"save":1,"error":2,"reason":3,"later":1,"vendor":1,"lexcept":1,"descript":1,"unknown":1,"object":1,"non":1,"syntax":1,"caus":4,"given":1,"indicatingth":1,"retriev":1,"method":1,"lstate":1,"construct":1,"initi":2,"exist":1,"lsyntax":1},"maxFreq":4,"totalTerms":32},"loc":3}