{"id":21259,"className":"java.util.ConcurrentModificationException","methodName":"ConcurrentModificationException","signature":"\u003cjava.util.ConcurrentModificationException: void ConcurrentModificationException(java.lang.Throwable)\u003e","javadoc":"/** \n * Constructs a new exception with the specified cause and a detail message of  {@code (cause\u003d\u003dnull ? null : cause.toString())} (whichtypically contains the class and detail message of  {@code cause}.\n * @param cause the cause (which is saved for later retrieval by the{@link Throwable#getCause()} method).  (A {@code null} value ispermitted, and indicates that the cause is nonexistent or unknown.)\n * @since  1.7\n */\n","tf":{"freq":{"except":2,"detail":2,"save":1,"nonexist":1,"later":1,"concurr":1,"messag":2,"link":1,"unknown":1,"whichtyp":1,"specifi":1,"ispermit":1,"caus":8,"indic":1,"retriev":1,"string":1,"contain":1,"valu":1,"method":1,"throwabl":1,"construct":1,"modif":1},"maxFreq":8,"totalTerms":32},"loc":3}