{"id":13096,"className":"java.lang.ClassNotFoundException","methodName":"getException","signature":"\u003cjava.lang.ClassNotFoundException: java.lang.Throwable getException()\u003e","javadoc":"/** \n * Returns the exception that was raised if an error occurred while attempting to load the class. Otherwise, returns \u003ctt\u003enull\u003c/tt\u003e. \u003cp\u003eThis method predates the general-purpose exception chaining facility. The  {@link Throwable#getCause()} method is now the preferred means ofobtaining this information.\n * @return the \u003ccode\u003eException\u003c/code\u003e that was raised while loading a class\n * @since 1.2\n */\n","tf":{"freq":{"facil":1,"attempt":1,"otherwis":1,"except":4,"error":1,"link":1,"predat":1,"general":1,"inform":1,"caus":1,"rais":2,"now":1,"chain":1,"mean":1,"purpos":1,"ofobtain":1,"load":2,"method":2,"throwabl":1,"prefer":1,"occur":1},"maxFreq":4,"totalTerms":27},"loc":3}