{"id":13211,"className":"java.lang.ExceptionInInitializerError","methodName":"getException","signature":"\u003cjava.lang.ExceptionInInitializerError: java.lang.Throwable getException()\u003e","javadoc":"/** \n * Returns the exception that occurred during a static initialization that caused this error to be created. \u003cp\u003eThis method predates the general-purpose exception chaining facility. The  {@link Throwable#getCause()} method is now the preferred means ofobtaining this information.\n * @return the saved throwable object of this\u003ccode\u003eExceptionInInitializerError\u003c/code\u003e, or \u003ccode\u003enull\u003c/code\u003e if this \u003ccode\u003eExceptionInInitializerError\u003c/code\u003e has no saved throwable object.\n */\n","tf":{"freq":{"facil":1,"except":5,"save":2,"error":3,"creat":1,"link":1,"predat":1,"object":2,"general":1,"inform":1,"caus":2,"now":1,"chain":1,"mean":1,"purpos":1,"ofobtain":1,"method":2,"throwabl":3,"initi":3,"prefer":1,"occur":1},"maxFreq":5,"totalTerms":35},"loc":3}