{"id":13246,"className":"java.lang.RuntimeException","methodName":"RuntimeException","signature":"\u003cjava.lang.RuntimeException: void RuntimeException(java.lang.Throwable)\u003e","javadoc":"/** \n * Constructs a new runtime exception with the specified cause and a detail message of \u003ctt\u003e(cause\u003d\u003dnull ? null : cause.toString())\u003c/tt\u003e (which typically contains the class and detail message of \u003ctt\u003ecause\u003c/tt\u003e).  This constructor is useful for runtime exceptions that are little more than wrappers for other throwables.\n * @param cause the cause (which is saved for later retrieval by the{@link #getCause()} method).  (A \u003ctt\u003enull\u003c/tt\u003e value ispermitted, and indicates that the cause is nonexistent or unknown.)\n * @since  1.4\n */\n","tf":{"freq":{"littl":1,"except":3,"detail":2,"save":1,"nonexist":1,"later":1,"messag":2,"link":1,"runtim":3,"typic":1,"use":1,"unknown":1,"specifi":1,"ispermit":1,"caus":8,"indic":1,"wrapper":1,"retriev":1,"string":1,"contain":1,"valu":1,"method":1,"throwabl":1,"construct":1,"constructor":1},"maxFreq":8,"totalTerms":38},"loc":3}