{"id":13475,"className":"java.lang.Exception","methodName":"Exception","signature":"\u003cjava.lang.Exception: void Exception(java.lang.String,java.lang.Throwable)\u003e","javadoc":"/** \n * Constructs a new exception with the specified detail message and cause.  \u003cp\u003eNote that the detail message associated with {@code cause} is \u003ci\u003enot\u003c/i\u003e automatically incorporated inthis exception\u0027s detail message.\n * @param message the detail message (which is saved for later retrievalby the  {@link #getMessage()} method).\n * @param cause the cause (which is saved for later retrieval by the{@link #getCause()} method).  (A \u003ctt\u003enull\u003c/tt\u003e value ispermitted, and indicates that the cause is nonexistent or unknown.)\n * @since  1.4\n */\n","tf":{"freq":{"inthi":1,"except":3,"detail":4,"save":2,"nonexist":1,"later":2,"messag":6,"incorpor":1,"link":2,"unknown":1,"automat":1,"specifi":1,"ispermit":1,"caus":6,"indic":1,"associ":1,"retriev":1,"valu":1,"method":2,"construct":1,"retrievalbi":1,"note":1},"maxFreq":6,"totalTerms":41},"loc":3}