{"id":27537,"className":"javax.xml.crypto.URIReferenceException","methodName":"URIReferenceException","signature":"\u003cjavax.xml.crypto.URIReferenceException: void URIReferenceException(java.lang.String,java.lang.Throwable,javax.xml.crypto.URIReference)\u003e","javadoc":"/** \n * Constructs a new \u003ccode\u003eURIReferenceException\u003c/code\u003e with the specified detail message, cause and \u003ccode\u003eURIReference\u003c/code\u003e. \u003cp\u003eNote that the detail message associated with \u003ccode\u003ecause\u003c/code\u003e is \u003ci\u003enot\u003c/i\u003e automatically incorporated in this exception\u0027s detail message.\n * @param message the detail message\n * @param cause the cause (A \u003ctt\u003enull\u003c/tt\u003e value is permitted, andindicates that the cause is nonexistent or unknown.)\n * @param uriReference the \u003ccode\u003eURIReference\u003c/code\u003e that was beingdereferenced when the error was encountered\n * @throws NullPointerException if \u003ccode\u003euriReference\u003c/code\u003e is\u003ccode\u003enull\u003c/code\u003e\n */\n","tf":{"freq":{"except":4,"detail":4,"error":1,"nonexist":1,"messag":5,"incorpor":1,"permit":1,"irefer":3,"beingdereferenc":1,"unknown":1,"uri":2,"automat":1,"specifi":1,"caus":5,"refer":3,"associ":1,"encount":1,"pointer":1,"valu":1,"construct":1,"andind":1,"note":1},"maxFreq":5,"totalTerms":41},"loc":7}