{"id":28107,"className":"javax.security.auth.Subject","methodName":"getPrivateCredentials","signature":"\u003cjavax.security.auth.Subject: java.util.Set\u003cjava.lang.Object\u003e getPrivateCredentials()\u003e","javadoc":"/** \n * Return the \u003ccode\u003eSet\u003c/code\u003e of private credentials held by this \u003ccode\u003eSubject\u003c/code\u003e. \u003cp\u003e The returned \u003ccode\u003eSet\u003c/code\u003e is backed by this Subject\u0027s internal private Credential \u003ccode\u003eSet\u003c/code\u003e.  Any modification to the returned \u003ccode\u003eSet\u003c/code\u003e affects the internal private Credential \u003ccode\u003eSet\u003c/code\u003e as well. \u003cp\u003e A caller requires permissions to access the Credentials in the returned \u003ccode\u003eSet\u003c/code\u003e, or to modify the \u003ccode\u003eSet\u003c/code\u003e itself.  A \u003ccode\u003eSecurityException\u003c/code\u003e is thrown if the caller does not have the proper permissions. \u003cp\u003e While iterating through the \u003ccode\u003eSet\u003c/code\u003e, a \u003ccode\u003eSecurityException\u003c/code\u003e is thrown if the caller does not have permission to access a particular Credential.  The \u003ccode\u003eIterator\u003c/code\u003e is nevertheless advanced to next element in the \u003ccode\u003eSet\u003c/code\u003e. \u003cp\u003e\n * @return  A \u003ccode\u003eSet\u003c/code\u003e of private credentials held by this\u003ccode\u003eSubject\u003c/code\u003e.\n */\n","tf":{"freq":{"caller":3,"element":1,"held":2,"thrown":2,"except":2,"credenti":7,"subject":3,"next":1,"particular":1,"back":1,"well":1,"access":2,"affect":1,"nevertheless":1,"secur":2,"requir":1,"advanc":1,"modifi":1,"intern":2,"permiss":3,"proper":1,"iter":2,"modif":1},"maxFreq":7,"totalTerms":42},"loc":14}