{"id":26928,"className":"javax.xml.transform.TransformerException","methodName":"initCause","signature":"\u003cjavax.xml.transform.TransformerException: java.lang.Throwable initCause(java.lang.Throwable)\u003e","javadoc":"/** \n * Initializes the \u003ci\u003ecause\u003c/i\u003e of this throwable to the specified value. (The cause is the throwable that caused this throwable to get thrown.) \u003cp\u003eThis method can be called at most once.  It is generally called from within the constructor, or immediately after creating the throwable.  If this throwable was created with  {@link #TransformerException(Throwable)} or{@link #TransformerException(String,Throwable)}, this method cannot be called even once.\n * @param cause the cause (which is saved for later retrieval by the{@link #getCause()} method).  (A \u003ccode\u003enull\u003c/code\u003e value ispermitted, and indicates that the cause is nonexistent or unknown.)\n * @return  a reference to this \u003ccode\u003eThrowable\u003c/code\u003e instance.\n * @throws IllegalArgumentException if \u003ccode\u003ecause\u003c/code\u003e is thisthrowable.  (A throwable cannot be its own cause.)\n * @throws IllegalStateException if this throwable wascreated with  {@link #TransformerException(Throwable)} or{@link #TransformerException(String,Throwable)}, or this method has already been called on this throwable.\n */\n","tf":{"freq":{"call":4,"save":1,"link":5,"state":1,"specifi":1,"transform":4,"indic":1,"refer":1,"valu":2,"immedi":1,"initi":1,"constructor":1,"argument":1,"thisthrow":1,"thrown":1,"except":6,"nonexist":1,"creat":2,"later":1,"init":1,"unknown":1,"wascreat":1,"illeg":2,"general":1,"instanc":1,"ispermit":1,"caus":10,"retriev":1,"string":2,"alreadi":1,"method":4,"even":1,"within":1,"throwabl":13},"maxFreq":13,"totalTerms":77},"loc":15}