{"id":23078,"className":"java.util.concurrent.RejectedExecutionException","methodName":"RejectedExecutionException","signature":"\u003cjava.util.concurrent.RejectedExecutionException: void RejectedExecutionException()\u003e","javadoc":"/** \n * Constructs a \u003ctt\u003eRejectedExecutionException\u003c/tt\u003e with no detail message. The cause is not initialized, and may subsequently be initialized by a call to  {@link #initCause(Throwable) initCause}.\n */\n","tf":{"freq":{"call":1,"except":2,"detail":1,"may":1,"reject":2,"messag":1,"link":1,"init":2,"caus":3,"throwabl":1,"construct":1,"initi":2,"execut":2,"subsequ":1},"maxFreq":3,"totalTerms":21},"loc":1}