{"id":26704,"className":"javax.xml.ws.ProtocolException","methodName":"ProtocolException","signature":"\u003cjavax.xml.ws.ProtocolException: void ProtocolException(java.lang.String,java.lang.Throwable)\u003e","javadoc":"/** \n * Constructs a new runtime exception with the specified detail message and cause. Note that the detail message associated with  cause is not automatically incorporated in  this runtime exception\u0027s detail message.\n * @param message the detail message (which is saved for later retrieval  bythe Throwable.getMessage() method).\n * @param cause the cause (which is saved for later retrieval by the\u003ccode\u003eThrowable.getCause()\u003c/code\u003e method). (A \u003ccode\u003enull\u003c/code\u003e value is  permitted, and indicates that the cause is nonexistent or  unknown.)\n */\n","tf":{"freq":{"protocol":1,"except":3,"detail":4,"save":2,"nonexist":1,"later":2,"messag":6,"incorpor":1,"permit":1,"runtim":2,"unknown":1,"automat":1,"specifi":1,"caus":6,"indic":1,"associ":1,"byth":1,"retriev":2,"valu":1,"method":2,"throwabl":2,"construct":1,"note":1},"maxFreq":6,"totalTerms":44},"loc":3}