{"id":22293,"className":"org.apache.commons.math.MathRuntimeException","methodName":"MathRuntimeException","signature":"\u003corg.apache.commons.math.MathRuntimeException: void MathRuntimeException(java.lang.Throwable,org.apache.commons.math.exception.util.Localizable,java.lang.Object[])\u003e","javadoc":"/** \n * Constructs a new \u003ccode\u003eMathRuntimeException\u003c/code\u003e with specified formatted detail message and nested \u003ccode\u003eThrowable\u003c/code\u003e root cause. Message formatting is delegated to  {@link java.text.MessageFormat}.\n * @param rootCause the exception or error that caused this exceptionto be thrown.\n * @param pattern format specifier\n * @param arguments format arguments\n * @since 2.2\n */\n","tf":{"freq":{"argument":2,"exceptionto":1,"thrown":1,"text":1,"except":3,"detail":1,"error":1,"root":2,"messag":3,"link":1,"runtim":2,"nest":1,"format":5,"specifi":2,"math":2,"deleg":1,"caus":3,"pattern":1,"java":1,"construct":1,"throwabl":1},"maxFreq":5,"totalTerms":36},"loc":5}