{"id":12152,"className":"javax.naming.event.NamingExceptionEvent","methodName":"getException","signature":"\u003cjavax.naming.event.NamingExceptionEvent: javax.naming.NamingException getException()\u003e","javadoc":"/** \n * Retrieves the exception that was thrown.\n * @return The exception that was thrown.\n */\n","tf":{"freq":{"thrown":2,"except":3,"retriev":1},"maxFreq":3,"totalTerms":6},"loc":3}